apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    generativelanguage.googleapis.com/type: applet
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 550.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/maxScale: '20'
  labels:
    cloud.googleapis.com/location: us-west1
    managed-by: google-ai-studio
  name: kinetiq-ai-product-database
  namespace: '<YOUR_PROJECT_NUMBER>'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/base-images: '{"":"us-central1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22"}'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 550.0.0
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/sessionAffinity: 'false'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: API_KEY
          value: <YOUR_API_KEY>
        image: <YOUR_IMAGE_URL>
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: <YOUR_SERVICE_ACCOUNT>
      timeoutSeconds: 300
